### ISSUE TITLE
모두 할일 : Titanium 개발환경 구축

### ISSUE THREAD

**Issue by kimdeokyun** [kosslab-kr/Titanium-SaveMyFriend#1]
Appcelerator에서 IDE설치, (https://platform.appcelerator.com/#/product/studio)

**Comment by gimdongwoo** [comment]
https://www.youtube.com/playlist?list=PLAQybJIBW2UuW3_CzBTmnJq_ULw4zp4bu

위 동영상 강의를 차례로 학습하여 Titanium 개발환경을 구축합니다.

하면서 어려운 점이나 문제를 코멘트로 공유합니다.

**Comment by jaeeonjin** [comment]
Appcelerator Studio 설치 완료 했습니다.
도움이 되실 지 모르겠지만 설치 과정 중 오류 있었던 부분 적어놓고 가겠습니다.
- 첫 번째 오류 : 설치 후 실행시 jvm오류가 났었는데 이것은 jdk 1.8.x 말고 1.6.x 버전으로 설치하시면 해결됩니다.
- 두 번째 오류 : 실행 후 Workspace 경로 설정 후 확인 누르고 프로그램이 실행될 시  에러메세지 중 magor.minor 51.0 이런 에러가 있었는데 구글링 결과 jdk 1.7.x 버전으로 설치하시면 해결됩니.

**Comment by Hyeongpil** [comment]
설치 완료했습니다.
