### ISSUE TITLE
모두 할일 : sourcetree를 이용한 git과 github 사용법 학습

### ISSUE THREAD

**Issue by gimdongwoo** [kosslab-kr/Titanium-SaveMyFriend#11]
http://hackersstudy.tistory.com/41
를 참고하여 리파지터리에 소스 변경점을 push 해 봅니다.

(방법)
자신의 github계정으로 리파지터리를 만들고 테스트로 commit과 push를 해 봅니다.

(이후)
연습 이후에는 
https://github.com/kosslab-kr/Titanium-SaveMyFriend 리파지터리를 로컬에 받아봅니다.
Create/New에서 Clone Repository를 이용합니다.

*\* (이후) 파트까지 성공한 사람들은 댓글 달아주세요.

**Comment by ChiHyeonKim** [comment]
성공했습니다~

**Comment by jaeeonjin** [comment]
성공했습니다!

**Comment by suprodigy** [comment]
성공했습니다~

**Comment by kimdeokyun** [comment]
성공했습니다~

**Comment by Hyeongpil** [comment]
성공했습니다!

**Comment by ykhaam** [comment]
성공했습니다!
