### ISSUE TITLE
팀장의 할일 : 팀원 각자의 역할을 정리

### ISSUE THREAD

**Issue by gimdongwoo** [kosslab-kr/Titanium-SaveMyFriend#12]
해카톤 기간 동안 각각의 팀원이 맡은 할일을 간단히 정리해주세요.

**Comment by kimdeokyun** [comment]
재언, 덕윤 - sms 파싱 및 필터 로직 구현, sms 발송 구현
형필, 정래 - 휴대폰 내의 전화번호부 불러오기, 중복 제거 구현
유경 - 어플리케이션 UI 제작
치현, 준영 - 앱 디버깅 및 에러 수정
