### ISSUE TITLE
모두 할일 : 타이타늄 샘플 코드 실행해 보기

### ISSUE THREAD

**Issue by gimdongwoo** [kosslab-kr/Titanium-SaveMyFriend#13]
https://github.com/appcelerator-developer-relations/appc-sample-rss

위 리파지터리의 샘플코드를 Studio로 import해서 실행해 봅니다.

시뮬레이터로 돌려도 되고, 직접 안드로이드 스마트폰에서도 돌려볼 수 있습니다.

안드로이드 스마트폰은 "usb 디버깅 허용"이라고 검색해보면 스마트폰 자체에서 해야할 설정이 필요합니다.

**Comment by kimdeokyun** [comment]
http://editorizer.tistory.com/224

개발자 옵션 실행 하는 방법에 대해 정리해 둔 블로그 입니다. 참고하시면 될 것 같습니다.

**Comment by ChiHyeonKim** [comment]
아래와 같이 오류가 뜨는데 재로그인을 어디서 해야 할까요?
![image](https://cloud.githubusercontent.com/assets/22412057/18813724/2d0af28a-833f-11e6-98ad-76236b8e9350.png)

**Comment by kimdeokyun** [comment]
임포팅하는 방법은 file - import로 들어가셔서 General - Existing Projects into Workspace 에서 로컬 리파지터리 경로를 설정해주시면 됩니다.
