### ISSUE TITLE
팀장 : 발표 PPT 제작

### ISSUE THREAD

**Issue by kimdeokyun** [kosslab-kr/Titanium-SaveMyFriend#25]

**Comment by ykhaam** [comment]
[발표ppt2.pptx](https://github.com/kosslab-kr/Titanium-SaveMyFriend/files/500469/ppt2.pptx)

혹시 글씨 깨질까봐 읽기 전용으로 해놨어요! 그래서 다른 분은 편집이 불가능합니다.ㅠㅠ
아직 뭐 한건 없지만 일단 올려봐요...
중간에 비워 놓은 부분은 실제 저희가 만든 어플리케이션 구동 화면을 
캡쳐하면서 설명했으면 하는데 해주실 수 있을까요?
2분밖에 안되기 때문에 간단간단히 설명해야할 것 같아요!!
맨 뒤에 조원 설명은 발표에서는 언급안하셔도 될 것 같아요! 예의상 넣어놓음....ㅋㅋㅋㅋ
제가 손이 너무 느려서ㅠㅠㅠㅠ

**Comment by kimdeokyun** [comment]
글씨체도 같이 저장해서 올려주실 수 있나요...?

**Comment by ykhaam** [comment]
오늘 학교가서 그렇게 할게요!

**Comment by ykhaam** [comment]
[따오기.zip](https://github.com/kosslab-kr/Titanium-SaveMyFriend/files/502034/default.zip)
