### ISSUE TITLE
재언, 덕윤 : 재난 문자 파싱 - sms 파싱, 스위치 제어

### ISSUE THREAD

**Issue by kimdeokyun** [kosslab-kr/Titanium-SaveMyFriend#3]
재언, 덕윤
- sms 파싱 및 "재난 문자" 필터링
  -

**Comment by ChiHyeonKim** [comment]
재난 문자 필터링을 위해서 참고가 될 만한 사이트를 적어봤습니다.
1. 재난 문자 개념
   https://namu.wiki/w/%EA%B8%B4%EA%B8%89%EC%9E%AC%EB%82%9C%EB%AC%B8%EC%9E%90
2. 재난 문자 사례
   https://namu.wiki/w/%EA%B8%B4%EA%B8%89%EC%9E%AC%EB%82%9C%EB%AC%B8%EC%9E%90/%EC%82%AC%EB%A1%80
3. 재난 문자 종류
   http://www.sisunnews.co.kr/news/articleView.html?idxno=39718
4. 재난 문자와 일반 문자의 차이점
   좀 더 찾고나서 추가 하도록 하겠습니다

**Comment by ChiHyeonKim** [comment]
1. CBS 기술 설명과 재난문자 송출 기준
   http://211.236.67.11:8080/WEB/

**Comment by kimdeokyun** [comment]
재난 문자 발송 기록 입니다. 재난 문자 포맷을 어느정도 알 수 있을 것 같습니다.
http://www.mpss.go.kr/home/news/disasterInfo/drSms/
