### ISSUE TITLE
유경 : 어플리케이션 UI 제작

### ISSUE THREAD

**Issue by kimdeokyun** [kosslab-kr/Titanium-SaveMyFriend#6]
- 사용자에게 편리한 UI를 제공한다.
  - "재난 문자"를 재발신하는 어플의 주제와 부합하게 제작.

**Comment by ykhaam** [comment]
[uiui.pptx](https://github.com/kosslab-kr/Titanium-SaveMyFriend/files/492271/uiui.pptx)

**Comment by ykhaam** [comment]
그때 회의를 바탕으로 대충 레이아웃 만들었는데 피드백이나 의견부탁드리겠습니다!! 아직 정식 디자인은 아니구 구성이에요!

**Comment by ChiHyeonKim** [comment]
전반적으로 깔끔해서 괜찮은거 같아요! 근데 문자보낼 사람 추가할때 저번에 말했던 경고문 (문자 보낼시에는 요금제에 따라 문자 요금이 과금될수도 있다) 이 빠져있어서 추가해주시면 더 좋을 거 같아요 ㅋㅋㅋ

**Comment by ykhaam** [comment]
의견 감사드립니다!! 그 경고문은 어떻게 추가하는게 좋을까요!!😂😂번호 추가한 후에 나타나는지, 아니면 추가하기 전에 경고문이 뜨는 것 중에 고민되서요!ㅠㅠ

**Comment by jaeeonjin** [comment]
문자 보내기 버튼을 클릭할 때 과금될 수 있다는 경고문 띄워주면 좋지 않을까요?!?!?!?!

**Comment by kimdeokyun** [comment]
처음 구상은 앱 백그라운드에서 자동적으로 보내주는 것이었는데, 액티비티에서 발송하게 버튼 누르는 것도 괜찮은 것 같습니다. ~

**Comment by jaeeonjin** [comment]
아 제가 그 점을 깜빡했네요 백그라운드에서 자동으로 즉각적으로 보내는게 맞는 것 같습니다

**Comment by ykhaam** [comment]
넵 참고해서 일단 만들어 볼게요! 나중에 안써도 괜찮으니까..!ㅎㅎ

**Comment by ykhaam** [comment]
![mainmain png](https://cloud.githubusercontent.com/assets/22412028/18917547/146ddb02-85d3-11e6-97c0-20ab6d1be321.jpg)


어..도움이 될까 하여 열심히 메인화면을...만들어봤어요ㅋㅋㅋㅋ
좀 허접하지만 쓸일이 있다면 써주세요! 하핳ㅎ...

**Comment by gimdongwoo** [comment]
@ykhaam 님 멋지네요. 다른 화면들도 디자인 해보면 좋을것 같습니다.

**Comment by ykhaam** [comment]
@gimdongwoo
넵 알겠습니다! 열심히 해볼게요!!

**Comment by yjy0431** [comment]
아 메인화면이 너무 예뻐서 못봤는데 일부러 hackerton이라고 하신건가요?

**Comment by ykhaam** [comment]
억 이거 초기에 대충만들어서 못봤네요....! 스펠링 고치는 것보다 지우는 게 나을 것 같아요!! 감사합니다😭😭😭

**Comment by kimdeokyun** [comment]
완전 이쁩니다 . 이거 상받을거같은데..! 앱 주제도 포함되어있구요

**Comment by ykhaam** [comment]
@kimdeokyun

으어ㅠㅠ 팀에 도움이 되었으면 좋겠어요! 다른 것도 열심히 만들어볼게요!

**Comment by yjy0431** [comment]
저거만든거면 충분하다고 봅니다. 진짜 디자이너가 돈받고 만든느낌;

**Comment by ykhaam** [comment]
![mainfinal png](https://cloud.githubusercontent.com/assets/22412028/18923674/2a673a42-85e8-11e6-989d-64c1ebeecbad.jpg)

~수정~

**Comment by ykhaam** [comment]
[app.zip](https://github.com/kosslab-kr/Titanium-SaveMyFriend/files/502796/app.zip)
